[workspace]
members = [
    "zksync-error-codegen-cli",
    "zksync-error-codegen",
]
resolver = "2"

[workspace.package]
authors = [
    "Igor Zhirkov <iz@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.1.0"
