component_name = "sequencer"
component_code = 1

[[errors]]
name = "ErrorDefinedExternally"
code = 3
message = "It's wrong! {index}"

  [[errors.fields]]
  name = "index"
  type = "uint"

  [errors.doc]
  description = "This error is defined in a small, non-intimidating file."
  short_description = ""
  likely_causes = [ ]
  references = [ "https://matter-labs.io", "https://github.com" ]

[[errors]]
name = "AnotherErrorDefinedExternally"
code = 4
message = "It's so wrong! {index}"

  [[errors.fields]]
  name = "index"
  type = "uint"

  [[errors.fields]]
  name = "two"
  type = "uint"

  [errors.doc]
  description = "The compiler is unable to find the file with the source code that it needs"
  short_description = "No input file"
  references = [ "https://matter-labs.io", "https://github.com" ]

    [[errors.doc.likely_causes]]
    cause = "You did not provide a file to compile"
    fixes = [
  "Check if you have provided a correct Solidity or YUL file to compile."
]
    report = "https://matter-labs.io"

      [errors.doc.likely_causes.owner]
      name = "solc"
      version = "> 1.0.0"
