[[domains]]
domain_name = "compiler"
domain_code = 1
identifier_encoding = "comp"
description = "Errors in compilers: zksolc, solc, zkvyper, etc."

[domains.bindings]
rust = "Compiler"

[[domains]]
domain_name = "core"
domain_code = 2
identifier_encoding = "core"
description = "Errors in core components such as sequencer"

[domains.bindings]
rust = "Core"

[[components]]
component_name = "zksolc"
domain = "compiler"
component_code = 1
identifier_encoding = "zksolc"
description = "Errors in zksolc compiler"

[components.bindings]
rust = "Zksolc"

[[components]]
component_name = "sequencer"
domain = "core"
component_code = 1
identifier_encoding = "seq"
description = "Errors in core components such as sequencer"
takeFrom = [
  "errors-core-1.json",
  "https://raw.githubusercontent.com/sayon/error-codegen-poc/refs/heads/main/errors-core-2.json"
]

[components.bindings]
rust = "Sequencer"

[[errors]]
name = "Umbrella"
code = 42
domain = "compiler"
component = "zksolc"
message = "Any error!"

[errors.bindings.rust]
name = "Umbrella"

[[errors.fields]]
name = "inner"
type = "WrappedError"

[[errors]]
name = "SolcNotFound"
code = 1
message = "I just can't find solc!"

[errors.bindings.rust]
name = "SolcNotFound"

[[errors.fields]]
name = "path"
type = "string"

[[errors.fields]]
name = "payload"
type = "uint"

[[errors]]
name = "FileNotFound"
code = 2
message = "Can't find the file {path} to compile."

[errors.bindings.rust]
name = "SolcNotFound"

[[errors.fields]]
name = "path"
type = "string"

[[errors.fields]]
name = "file_index"
type = "uint"

[errors.doc]
description = "The compiler is unable to find the file with the source code that it needs"
short_description = "No input file"
references = [ "https://matter-labs.io", "https://github.com" ]

[[errors.doc.likely_causes]]
cause = "You did not provide a file to compile"
fixes = [
  "Check if you have provided a correct Solidity or YUL file to compile."
]

[errors.doc.likely_causes.owner]
name = "solc"
version = "> 1.0.0"
